FAIL
Kernel panic in run: PANIC at ../../threads/interrupt.c:224 in intr_yield_on_return(): assertion `intr_context ()' failed.
Call stack: 0xc0028429 0xc002143b 0xc0020902 0xc0021110 0xc002b051 0xc002a32f 0xc00207d1 0xc0020771
Translation of call stack:
0xc0028429: debug_panic (.../../lib/kernel/debug.c:38)
0xc002143b: intr_yield_on_return (..../threads/interrupt.c:225)
0xc0020902: is_still_top (..../../threads/thread.c:626)
0xc0021110: thread_create (..../../threads/thread.c:217)
0xc002b051: test_priority_donate_multiple2 (...ity-donate-multiple2.c:45)
0xc002a32f: run_test (.../tests/threads/tests.c:57)
0xc00207d1: run_task (.../../../threads/init.c:292)
0xc0020771: run_actions (.../../../threads/init.c:341)
